#pragma once

#include "NativeGameplayTags.h"

namespace SFGameplayTags
{
	// Native Input Tags
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);

	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseQuickbar_1);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseQuickbar_2);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseQuickbar_3);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseQuickbar_4);

	// Ability Input Tags
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_PrimarySkill);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SecondarySkill);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_IdentitySkill);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dodge);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ToggleInventory);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LockOn);

	// Dummy Data
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AttackUpgrade);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_GroundUpgrade);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UltUpgrade);
}