#pragma once

#include "NativeGameplayTags.h"

namespace SFGameplayTags
{
	// Primary Stats
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_MaxHealth);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_MaxMana);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_MaxStamina);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_MoveSpeed);

	// Combat Stats
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_AttackPower);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Defense);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_AttackSpeed);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_CriticalChance);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_CriticalDamage);

	// Hero Stats
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Luck);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_CooldownRate);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_ManaRegen);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_StaminaRegen);
	SF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_ManaReduction);
}